import { useState } from 'react'
import { Link } from 'react-router-dom'
import toast from 'react-hot-toast'
import useLanguage from '../../hooks/use-language'
import useWebsiteContent from '../../hooks/use-website-content'
import { updateWebsiteContent } from '../../services/makeup-service'
import extractError from '../../services/extract-error'

export default function WebsiteContentForm(){const{language,t}=useLanguage();const{content,refresh}=useWebsiteContent();const[draft,setDraft]=useState(()=>({...content}));const[busy,setBusy]=useState(false);const field=(key:keyof typeof draft,label:string,multiline=false)=><label>{label}{multiline?<textarea value={String(draft[key])} onChange={event=>setDraft({...draft,[key]:event.target.value})}/>:<input value={String(draft[key])} onChange={event=>setDraft({...draft,[key]:event.target.value})}/>}</label>;async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);try{const{id,...payload}=draft;await updateWebsiteContent(payload);await refresh();toast.success(t('Website content updated.','تم تحديث محتوى الموقع.'))}catch(error){toast.error(extractError(error,language))}finally{setBusy(false)}}return <section className="form-panel course-editor"><p className="eyebrow">DOHA MUA · {t('ADMIN','الإدارة')}</p><h1>{t('Website content','محتوى الموقع')}</h1><form onSubmit={event=>void submit(event)}><fieldset><legend>{t('English content','المحتوى الإنجليزي')}</legend>{field('heroTitleEn',t('Hero title','عنوان الواجهة'))}{field('heroSubtitleEn',t('Hero subtitle','النص الفرعي للواجهة'),true)}{field('aboutEn',t('About Doha','عن ضحى'),true)}{field('bridalDescriptionEn',t('Bridal description','وصف العرائس'),true)}{field('studioAddressEn',t('Studio address message','رسالة عنوان الاستوديو'),true)}</fieldset><fieldset dir="rtl"><legend>{t('Arabic content','المحتوى العربي')}</legend>{field('heroTitleAr','عنوان الواجهة بالعربية')}{field('heroSubtitleAr','النص الفرعي للواجهة بالعربية',true)}{field('aboutAr','عن ضحى بالعربية',true)}{field('bridalDescriptionAr','وصف العرائس بالعربية',true)}{field('studioAddressAr','رسالة عنوان الاستوديو بالعربية',true)}</fieldset><fieldset><legend>{t('Contact details','بيانات التواصل')}</legend>{field('whatsappNumber',t('WhatsApp number','رقم واتساب'))}{field('contactEmail',t('Contact email','بريد التواصل'))}</fieldset><button disabled={busy}>{busy?t('Please wait...','يرجى الانتظار...'):t('Save content','حفظ المحتوى')}</button><Link className="button-secondary" to="/admin">{t('Cancel','إلغاء')}</Link></form></section>}
