import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

type Language = 'en' | 'ar'
const translations: Record<string, [string, string]> = {
  loading: ['Loading…','جارٍ التحميل…'], courses: ['Courses','الدورات'], academy: ['Academy','الأكاديمية'], lessons: ['lessons','دروس'], inLibrary: ['In your library','في مكتبتك'], viewCourse: ['View course','عرض الدورة'], collectionSoon: ['Our course collection is being prepared.','نعمل حاليًا على إعداد مجموعة الدورات.'], educationCollection: ['Education collection','مجموعة الدورات التعليمية'], educationTitle: ['Makeup education for the artist you are becoming.','تعليم مكياج للفنانة التي تطمحين إليها.'], educationIntro: ['Watch beautiful technique become reliable, repeatable artistry.','شاهدي التقنية الراقية تتحول إلى فن موثوق وقابل للتطبيق.'],
  login: ['Login','تسجيل الدخول'], welcomeBack: ['Welcome back','مرحبًا بعودتك'], loginIntro: ['Sign in to access your makeup courses and account.','سجّلي الدخول للوصول إلى دورات المكياج وحسابك.'], email: ['Email','البريد الإلكتروني'], password: ['Password','كلمة المرور'], noAccount: ["Don't have an account?",'ليس لديك حساب؟'], registerNow: ['Register now','سجّلي الآن'], createAccount: ['Create account','إنشاء حساب'], startJourney: ['Start your artistry journey','ابدئي رحلتك الفنية'], registerIntro: ['Join DOHA MUA to learn and access your professional makeup courses.','انضمي إلى DOHA MUA للتعلّم والوصول إلى دورات المكياج الاحترافية.'], firstName: ['First name','الاسم الأول'], lastName: ['Last name','اسم العائلة'], alreadyMember: ['Already a member?','لديك حساب بالفعل؟'],
  myCourses: ['My courses','دوراتي'], accountLoading: ['Loading your account…','جارٍ تحميل حسابك…'], adminChecking: ['Checking administrator access…','جارٍ التحقق من صلاحيات الإدارة…'], pageNotFound: ['Page not found','الصفحة غير موجودة'], pageMissing: ['The page you tried to open does not exist.','الصفحة التي حاولت فتحها غير موجودة.'], backHome: ['Back home','العودة للرئيسية'],
  footerIntro: ['Professional makeup education and bridal artistry, thoughtfully held.','تعليم مكياج احترافي وفن عرائس بعناية واهتمام.'], adminWorkspace: ['Admin workspace','لوحة الإدارة'], bridalBooking: ['Bridal booking','حجز العروس'], privacy: ['Privacy Policy','سياسة الخصوصية'], bookingPolicy: ['Booking Policy','سياسة الحجز'], terms: ['Terms and Conditions','الشروط والأحكام'], rights: ['All rights reserved.','جميع الحقوق محفوظة.'], language: ['Language','اللغة'],
  contactWhatsApp: ['Contact on WhatsApp','تواصلي عبر واتساب'], askBooking: ['Ask about your booking','استفسري عن الحجز'], home: ['Home','الرئيسية'], pending: ['Pending','قيد الانتظار'], confirmed: ['Confirmed','مؤكد'], cancelled: ['Cancelled','ملغي'], completed: ['Completed','مكتمل'], status: ['Status','الحالة'], date: ['Date','التاريخ'], time: ['Time','الوقت'], reference: ['Booking reference','مرجع الحجز'], returnHome: ['Return to homepage','العودة إلى الرئيسية'],
  generalError: ['Something went wrong. Please try again.','حدث خطأ. يرجى المحاولة مرة أخرى.'], loginFailed: ['Email or password is incorrect.','البريد الإلكتروني أو كلمة المرور غير صحيحة.'], unauthorized: ['Please sign in to continue.','يرجى تسجيل الدخول للمتابعة.'], accessDenied: ['You do not have access to this content.','ليس لديك صلاحية للوصول إلى هذا المحتوى.'], unavailable: ['This appointment is no longer available.','هذا الموعد لم يعد متاحًا.'], duplicate: ['A recent booking request already used these details. Please wait before trying again.','تم إرسال طلب حديث بهذه البيانات. يرجى الانتظار قبل المحاولة مرة أخرى.'], invalidPhone: ['Please enter a valid Israeli phone number.','يرجى إدخال رقم هاتف إسرائيلي صالح.'], invalidEmail: ['Please enter a valid email address.','يرجى إدخال بريد إلكتروني صالح.'], required: ['Please complete all required fields.','يرجى إكمال جميع الحقول المطلوبة.'], policyRequired: ['Please agree to the booking policy and terms.','يرجى الموافقة على سياسة الحجز والشروط.']
}
type LanguageValue = { language: Language; setLanguage: (language: Language) => void; t: (english: string, arabic: string) => string; tr: (key: string) => string }
const LanguageContext = createContext<LanguageValue | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => localStorage.getItem('doha-mua-language') === 'ar' ? 'ar' : 'en')
  useEffect(() => { localStorage.setItem('doha-mua-language', language); document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr' }, [language])
  return <LanguageContext.Provider value={{ language, setLanguage, t: (english, arabic) => language === 'ar' ? arabic : english, tr: key => translations[key]?.[language === 'ar' ? 1 : 0] || key }}>{children}</LanguageContext.Provider>
}
export default function useLanguage() { const value = useContext(LanguageContext); if (!value) throw new Error('LanguageProvider is missing'); return value }
