export type CourseStatus = 'draft' | 'published'
export type AppointmentStatus = 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED'
export const VIDEO_PROVIDERS = { VdoCipher: 'VDOCIPHER' } as const
export type VideoProvider = typeof VIDEO_PROVIDERS[keyof typeof VIDEO_PROVIDERS]
export const VIDEO_STATUSES = { NotUploaded: 'NOT_UPLOADED', Processing: 'PROCESSING', Ready: 'READY' } as const
export type VideoStatus = typeof VIDEO_STATUSES[keyof typeof VIDEO_STATUSES]
export type Course = { id: number; title: string; titleEn?: string | null; titleAr?: string | null; shortDescription: string; shortDescriptionEn?: string | null; shortDescriptionAr?: string | null; description: string; descriptionEn?: string | null; descriptionAr?: string | null; price: number; salePrice?: number | null; payablePrice: number; isFeatured: boolean; imageUrl: string; instructorName: string; instructorNameEn?: string | null; instructorNameAr?: string | null; instructorBio: string; instructorBioEn?: string | null; instructorBioAr?: string | null; status: CourseStatus; lessons: Lesson[]; isPurchased: boolean }
export type Lesson = { id: number; title: string; titleEn?: string | null; titleAr?: string | null; description: string; descriptionEn?: string | null; descriptionAr?: string | null; position: number; videoStatus: VideoStatus; videoProvider?: VideoProvider | string | null; videoId?: string | null; playbackReference?: string | null }
export type ProtectedVideoPlayback = { provider: 'vdocipher'; otp: string; playbackInfo: string; expiresIn: number }
export type Availability = { id: number; date: string; startTime: string; endTime: string; isAvailable: boolean }
export type BookingPaymentStatus = 'PENDING' | 'SUCCESS' | 'FAILED' | 'CANCELLED' | 'REFUND_REQUIRED' | 'REFUNDED'
export type BookingPayment = { id: number; amount: string; currency: string; provider: string; status: BookingPaymentStatus; createdAt: string }
export type Appointment = { id: number; brideName: string; email: string; phone: string; venue: string; eventType: string; city: string; peopleCount: number; preferredLanguage: 'en' | 'ar'; notes?: string; status: AppointmentStatus; createdAt: string; availability?: Availability; bookingPayment?: BookingPayment }
export type AdminDashboard = { students: number; courses: number; purchases: number; appointments: number; notifications: Array<{ id: number; type: 'purchase' | 'appointment'; message: string; isRead: boolean; createdAt: string }> }
export type AdminUser = { id: number; firstName: string; lastName: string; email: string; phone?: string; preferredLanguage?: 'en'|'ar'; role: 'student'|'admin'; isBlocked: boolean }
export type AdminPurchase = { id: number; amount: string; status: string; provider?: string; user?: AdminUser; course?: Course }
export type AdminUserDetail = { user: AdminUser; purchases: AdminPurchase[]; bookings: Appointment[] }
export type WebsiteContent = { id: number; heroTitleEn: string; heroTitleAr: string; heroSubtitleEn: string; heroSubtitleAr: string; aboutEn: string; aboutAr: string; bridalDescriptionEn: string; bridalDescriptionAr: string; studioAddressEn: string; studioAddressAr: string; whatsappNumber: string; contactEmail: string }
